version: "3.8"
volumes:
  postgres_data:
services:
  postgres:
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${PGUSER}
      TZ: Europe/Moscow
    ports:
      - 5432:5432
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 10s
      timeout: 3m
      retries: 20

  myhttpserver:
    build: ./
    ports:
      - 8081:8080
    depends_on:
      postgres:
        condition: service_healthy