output   = "models"
wipe     = true
no-tests = true
add-soft-deletes = true

[psql]
  user = "postgres"
  driver = "postgres"
  dbname = "postgres"
  host = "localhost"
  port = 5432
  pass = "postgres"
  sslmode = "disable"
  blacklist = ["migrations", "connection"]